# Generated by Django 5.2.3 on 2026-02-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stoppoints", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stoppoint",
            name="bonus_disbursed_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="Timestamp when the stop-point bonus was credited to the wallet.",
            ),
        ),
    ]
