# Generated by Django 5.2.3 on 2025-12-03 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userproducttask',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userproducttask',
            name='round_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='userproducttask',
            unique_together={('user', 'product', 'round_number')},
        ),
    ]
